### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by Celebes** [PacktPublishing/Full-Stack-Development-with-JHipster#1]
I am going through chapter 5 of the book. There are some errors in **product.component.html** that I wanted to fix by comparing to the source code.

`
    <div class="btn-group" role="group"
                 jhiSort [(predicate)]="predicate" [(ascending)]="reverse"
                 [callback]="transition.bind(this)">
`

Errors are:
* Unresolved variable or type "reverse"
* Unresolved variable or type "transition"

The problem is when I navigate to https://github.com/PacktPublishing/Full-Stack-Development-with-JHipster/tree/master/Chapter05/online-store/src/main/webapp/app there is only "vendor.ts" file?

**Comment by shubham763** [comment]
Hi @Celebes 
I've updated the repo, now there are all the files in the repository.
